name: Build & Deploy on GH Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install NPM packages
      run: npm install --force

    - name: Build project
      run: npm run build

    - name: Upload production-ready build files
      uses: actions/upload-pages-artifact@v1
      with:
        name: production-files
        path: ./build

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to gh-pages
      id: deployment
      uses: actions/deploy-pages@v1
